---
- name: add www-data group
  group:
    name: www-data
    state: present
    system: yes

- name: install nginx
  package:
    name: nginx
    state: latest
  notify:
    - restart nginx

- name: copy nginx config
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: open firewall ports for nginx
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - http
  when: ansible_distribution == 'CentOS'

- name: copy error files
  copy:
    src: files/html-root/{{ item }}
    dest: /usr/share/nginx/html/{{ item }}
  with_items:
    - 403.html
    - 404.html
    - 50x.html
